name: Build and publish API docs
on:
  push:
    branches:
      - master
env:
  nim-version: "stable"
  nim-src: src/jacket.nim
  deploy-dir: .gh-pages
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ env.nim-version }}
      - run: nimble install -y
      - run: nimble doc --index:on --project --git.url:https://github.com/${{ github.repository }} --git.commit:master --out:${{ env.deploy-dir }} ${{ env.nim-src }}
      - name: "Copy to index.html"
        run: cp ${{ env.deploy-dir }}/jacket.html ${{ env.deploy-dir }}/index.html
      - name: Deploy documents
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.deploy-dir }}
